### ISSUE TITLE
GQN Convert TFrecords script

### ISSUE THREAD

**Issue by eduardohenriquearnold** [masa-su/pixyzoo#10]
I am trying to reproduce the results and couldn't find the ```GQN/dataset/convert2torch.py``` file. I believe it wasn't added to the repository?
Thanks

**Comment by eduardohenriquearnold** [comment]
I just found the original file here, in case anyone needs it too.
https://github.com/iShohei220/torch-gqn/blob/master/dataset/convert2torch.py

**Comment by TMats** [comment]
@eduardohenriquearnold 
Thanks for reporting the trouble :)
I added the code.
https://github.com/masa-su/pixyzoo/commit/a7bd609bc4c0a138fd119baf744134ab77d18f63
